# HOWTO: https://pre-commit.com/#usage
# pip3 install pre-commit
# pre-commit install

repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      #    - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: detect-aws-credentials
        args:
          - --allow-missing-credentials
  - repo: https://github.com/ansible/ansible-lint.git
    rev: v6.18.0
    hooks:
      - id: ansible-lint
        files: \.(yaml|yml)$
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.5
    hooks:
      - id: shellcheck
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.0
    hooks:
      - id: gitleaks
        # The hook runs 'gitleaks protect --staged' which parses output of
        # 'git diff --staged', i.e. always passes in pre-push/manual stage.
        stages: [commit]

ci:
  # The project is too huge for pre-commit.ci
  skip: [ansible-lint]
