# Copyright Contributors to the Packit project.
# SPDX-License-Identifier: MIT

---
- name: Generate an OpenSSH keypair with the default values (4096 bits, rsa)
  openssh_keypair:
    path: "{{ generate_secrets_path }}/id_ed25519"
    type: "ed25519"
