# Copyright Contributors to the Packit project.
# SPDX-License-Identifier: MIT

---
- name: Generate config files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ generate_secrets_path }}/{{ item }}"
    mode: 0644
  loop:
    - packit-service.yaml.j2
    - extra-vars.yml
    - fedora.toml.j2
    - copr
    - ssh_config
