# Copyright Contributors to the Packit project.
# SPDX-License-Identifier: MIT

---
- name: Create empty files
  ansible.builtin.file:
    path: "{{ generate_secrets_path }}/{{ item }}"
    state: touch
    mode: 0644
  loop:
    - fedora.keytab
