# Copyright Contributors to the Packit project.
# SPDX-License-Identifier: MIT

---
- name: Check a deployment
  hosts: all
  vars:
    service: "{{ lookup('env', 'SERVICE') | default('packit', True) }}"
    deployment: "{{ lookup('env', 'DEPLOYMENT') }}"
    path_to_secrets: "{{ project_dir }}/secrets/{{ service }}/{{ deployment }}"
    postgres_version: 13
  tasks:
    - name: Include tasks/project-dir.yml
      ansible.builtin.include_tasks: tasks/project-dir.yml

    - name: Include variables
      ansible.builtin.include_vars: "{{ project_dir }}/vars/{{ service }}/{{ deployment }}.yml"

    - name: Include deployment facts
      ansible.builtin.include_tasks: tasks/set-deployment-facts.yml

    - name: Include tasks/set-facts.yml
      ansible.builtin.include_tasks: tasks/set-facts.yml

    - name: Include tasks/check-pod-running.yml
      ansible.builtin.include_tasks: tasks/check-pod-running.yml
      loop: "{{ deploymentconfigs + ['packit-worker'] }}"
