# Copyright Contributors to the Packit project.
# SPDX-License-Identifier: MIT

# Mimic what we do during deployment when we render secret files
# from their templates before we create k8s secrets from them.
---
- name: Process templates with data from extra-vars.yml
  hosts: all
  vars:
    service: "{{ lookup('env', 'SERVICE') | default('packit', True) }}"
    deployment: "{{ lookup('env', 'DEPLOYMENT') }}"
    tenant: packit # MP+ tenant
  tasks:
    - name: Include tasks/project-dir.yml
      ansible.builtin.include_tasks: tasks/project-dir.yml
      tags:
        - always

    - name: Include variables
      ansible.builtin.include_vars: "{{ project_dir }}/vars/{{ service }}/{{ deployment }}.yml"
      tags:
        - always

    - name: Include tasks/set-facts.yml
      ansible.builtin.include_tasks: tasks/set-facts.yml
      tags:
        - rendering-templates

    - name: Include extra secret vars
      ansible.builtin.include_vars:
        file: "{{ path_to_secrets }}/extra-vars.yml"
        name: vault

    - name: Process packit-service.yaml.j2 template
      ansible.builtin.template:
        src: "{{ path_to_secrets }}/packit-service.yaml.j2"
        dest: "{{ path_to_secrets }}/packit-service.yaml"
        mode: "0644"

    - name: Process fedora.toml.j2 template
      ansible.builtin.template:
        src: "{{ path_to_secrets }}/fedora.toml.j2"
        dest: "{{ path_to_secrets }}/fedora.toml"
        mode: "0644"
      when: service != 'stream'
