name: Rebuild & push base image
on:
  workflow_dispatch:
  schedule:
    # At 00:00 on Tuesday.
    - cron: "0 0 * * 2"
  push:
    branches:
      - main
    paths:
      - containers/Containerfile.fedora
      - containers/Containerfile.c9s

jobs:
  build:
    # To not run in forks
    if: github.repository_owner == 'packit'

    name: Build and push image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - containerfile: containers/Containerfile.fedora
            tags: "fedora"
          - containerfile: containers/Containerfile.c9s
            tags: "c9s latest"

    steps:
      - uses: actions/checkout@v3

      - name: Build Image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          containerfiles: ${{ matrix.containerfile }}
          image: base
          tags: ${{ matrix.tags }}
          # Uncomment once we stop using oc cluster up for tests
          #           oci: true

      - name: Push To Quay
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: quay.io/packit
          username: ${{ secrets.QUAY_IMAGE_BUILDER_USERNAME }}
          password: ${{ secrets.QUAY_IMAGE_BUILDER_TOKEN }}
